[package]
name = "relational_db_builder"
version = "0.1.0"
edition = "2021"

[lib]
name = "relational_db_builder"
path = "src/lib.rs"

[[bin]]
name = "relational_db_builder"
path = "src/main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres_db = { path = "../postgres_db" }
# semver_spec_serialization = { path = "../semver_spec_serialization" }
utils = { path = "../utils" }
metrics_logging = { path = "../metrics_logging" }

serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0.79", features = ["preserve_order"] }
indicatif = "0.16.2"
chrono = { version = "0.4.19", features = ["serde"] }
url = "2.3.0"
deepsize = { git = "https://github.com/anonymous-submit-1/deepsize", features = ["chrono", "serde_json"] }
lru = { git = "https://github.com/anonymous-submit-1/lru-rs" }
kdam = "0.3.0"

[dev-dependencies]
test-case = "2.1.0"
ron = "0.7.1"
criterion = { version = "0.3", features = ["html_reports"] }
glob = "0.3.0"
colored = "2.0.0"

#[[bench]]
#name = "insertion"
#harness = false