CREATE SCHEMA metadata_analysis;

ALTER DEFAULT PRIVILEGES IN SCHEMA metadata_analysis
GRANT ALL ON TABLES TO pinckney,
    federico;
ALTER DEFAULT PRIVILEGES IN SCHEMA metadata_analysis
GRANT ALL ON SEQUENCES TO pinckney,
    federico;
ALTER DEFAULT PRIVILEGES IN SCHEMA metadata_analysis
GRANT ALL ON FUNCTIONS TO pinckney,
    federico;
ALTER DEFAULT PRIVILEGES IN SCHEMA metadata_analysis
GRANT ALL ON TYPES TO pinckney,
    federico;

ALTER DEFAULT PRIVILEGES IN SCHEMA metadata_analysis
GRANT SELECT ON TABLES TO data_analyzer;
ALTER DEFAULT PRIVILEGES IN SCHEMA metadata_analysis
GRANT USAGE,
    SELECT ON SEQUENCES TO data_analyzer;
ALTER DEFAULT PRIVILEGES IN SCHEMA metadata_analysis
GRANT EXECUTE ON FUNCTIONS TO data_analyzer;
ALTER DEFAULT PRIVILEGES IN SCHEMA metadata_analysis
GRANT USAGE ON TYPES TO data_analyzer;

ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC
GRANT SELECT ON TABLES TO data_analyzer;
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC
GRANT USAGE,
    SELECT ON SEQUENCES TO data_analyzer;
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC
GRANT EXECUTE ON FUNCTIONS TO data_analyzer;
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC
GRANT USAGE ON TYPES TO data_analyzer;

ALTER DEFAULT PRIVILEGES
GRANT USAGE ON SCHEMAS TO data_analyzer;

GRANT ALL ON SCHEMA metadata_analysis TO federico;
GRANT ALL ON SCHEMA metadata_analysis TO pinckney;
GRANT USAGE ON SCHEMA metadata_analysis TO data_analyzer;