// include tests generated by `build.rs`, one test per json file in resources/test_changes/
include!(concat!(env!("OUT_DIR"), "/deserialize_change_tests.rs"));
// include!(concat!(env!("OUT_DIR"), "/process_changes_tests.rs"));
